submit50:
  files: &submit50_files
    - !exclude "*"
    - !include "*.py"
    - !require hello.py

check50:
  checks:
    hello world:
      - run: python3 hello.py
        stdout: Hello, world!
        exit: 0
